 const data=[
    {
        id:1,
        firstName:"Rushil",
        lastName:"patel",
        birthYear:"1903",
        workingHours:3,
    },
    {
        id:2,
        firstName:"shawami",
        lastName:"sayta",
        birthYear:"3455",
        workingHours:4,
    },{
        id:3,
        firstName:"kanko",
        lastName:"tokyoi",
        birthYear:"1233",
        workingHours:3,
    },{
        id:4,
        firstName:"jemit",
        lastName:"khakhu",
        birthYear:"5643",
        workingHours:5,
    },{
        id:5,
        firstName:"tako",
        lastName:"kaki",
        birthYear:"2135",
        workingHours:5,
    },{
        id:6,
        firstName:"natpii",
        lastName:"sui",
        birthYear:"7313",
        workingHours:1,
    },{
        id:7,
        firstName:"sathidar",
        lastName:"dar",
        birthYear:"1111",
        workingHours:1,
    },{
        id:8,
        firstName:"laule",
        lastName:"tule",
        birthYear:"53212",
        workingHours:8,
    }
]
export default data;